#!/bin/bash
# Ask the user for their name
echo Entrer Le Token Slack Utilisateur
read token_name
sed -i -e "s/token_place/`echo $token_name`/g" MDMBot/conf/conf_bot.py

pip install -r requirements.txt

path=$(sed -nr '/Location/p' < <(pip show pytest) | cut -d' ' -f2)

cp -r MDMBot $path

